export const TODO_ADDED = 'todos.TODO_ADDED'
export const TODO_UPDATED = 'todos.TODO_UPDATED'
export const TODO_DELETED = 'todos.TODO_DELETED'
export const TODOS_SYNCED = 'todos.TODOS_SYNCED'
export const TODOS_LOADED = 'todos.TODOS_LOADED'
